### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by Zimingcs** [javyduck/DiffSmooth#2]
Hi, the last pretrained file beit_large_patch16_224 cannot be downloaded without the account of Illinois. Could you please provide another accessible link?

**Comment by javyduck** [comment]
Hi, sorry for the late reply,

You can download it via this link:

https://uillinoisedu-my.sharepoint.com/:f:/g/personal/jiaweiz7_illinois_edu/EstdhnzHtXJIqhsNlv9q4nUBNcSjVvNp6pcj4ep3BTTVtg?e=QqfgIB

Thanks!
